services:
  db:
    image: mariadb:10.11
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - crud-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 6

  app:
    build: ./App
    depends_on:
      db:
        condition: service_healthy
    environment:
      PORT: ${PORT}
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      LOG_DIR: ${LOG_DIR}
    networks:
      - crud-network
    volumes:
      - ./logs:/var/logs/crud
    ports:
      - "8080:80"
    restart: unless-stopped

  fluent-bit:
    image: fluent/fluent-bit:4.0.13
    depends_on:
      - app
    volumes:
      - ./logs:/var/logs/crud:ro
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf:ro
      - ./parsers.conf:/fluent-bit/etc/parsers.conf:ro
    ports:
      - "2020:2020"
    networks:
      - crud-network
    restart: unless-stopped
    environment:
      - HOSTNAME=${HOSTNAME}
      - LOKI_HOST=${LOKI_HOST}
      - LOKI_PORT=${LOKI_PORT}
      - LOKI_JOB_LABEL=${LOKI_JOB_LABEL}


volumes:
  db_data:

networks:
  crud-network:
    driver: bridge